version: '3.1'

services: 
    db:
        image: "postgres"
        environment:
            POSTGRES_PASSWORD: helth123
            POSTGRES_USER: admin
            POSTGRES_DB: ehealth-care-db
        volumes:
            - database-data:/var/lib/postgresql/data
        ports:
            - "5532:5432"
volumes:
    database-data: